### ISSUE TITLE
Exception in rns service

### ISSUE THREAD

**Issue by pizdjuk** [markqvist/Reticulum#320]
after starting following appears:

```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/RNS/Transport.py", line 283, in jobloop
    Transport.jobs()
  File "/home/user/.local/lib/python3.8/site-packages/RNS/Transport.py", line 578, in jobs
    packet.send()
  File "/home/user/.local/lib/python3.8/site-packages/RNS/Packet.py", line 261, in send
    if RNS.Transport.outbound(self):
  File "/home/user/.local/lib/python3.8/site-packages/RNS/Transport.py", line 766, in outbound
    tx_time   = (len(packet.raw)*8) / interface.bitrate
```

**Comment by markqvist** [comment]
Hmm, I thought I had fixed that some time ago. What version of RNS are you running?

**Comment by pizdjuk** [comment]
> Hmm, I thought I had fixed that some time ago. What version of RNS are you running?

0.5.4

**Comment by pizdjuk** [comment]
It appears when I play around with system route tables

**Comment by markqvist** [comment]
> system route tables

The Reticulum path tables, or IP routes?

**Comment by pizdjuk** [comment]
> > system route tables
> 
> The Reticulum path tables, or IP routes?

with iptables on Linux host

**Comment by markqvist** [comment]
Moving to discussions then :)
