### ISSUE TITLE
Problem with receipt class

### ISSUE THREAD

**Issue by HarlekinSimplex** [markqvist/Reticulum#50]
Hi Mark,

today I saw the following error in the log:
```
nexus-test_node01    | Exception occurred during processing of request from ('172.25.0.1', 50998)
nexus-test_node01    | Traceback (most recent call last):
nexus-test_node01    |   File "/usr/local/lib/python3.9/socketserver.py", line 683, in process_request_thread
nexus-test_node01    |     self.finish_request(request, client_address)
nexus-test_node01    |   File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
nexus-test_node01    |     self.RequestHandlerClass(request, client_address, self)
nexus-test_node01    |   File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
nexus-test_node01    |     self.handle()
nexus-test_node01    |   File "/usr/local/lib/python3.9/http/server.py", line 425, in handle
nexus-test_node01    |     self.handle_one_request()
nexus-test_node01    |   File "/usr/local/lib/python3.9/http/server.py", line 413, in handle_one_request
nexus-test_node01    |     method()
nexus-test_node01    |   File "/bsb/nexus_server/nexus_server.py", line 1322, in do_POST
nexus-test_node01    |     command_result = process_command(post)
nexus-test_node01    |   File "/bsb/nexus_server/nexus_server.py", line 1386, in process_command
nexus-test_node01    |     success = cmd_add_message(message)
nexus-test_node01    |   File "/bsb/nexus_server/nexus_server.py", line 1495, in cmd_add_message
nexus-test_node01    |     distribute_message(message)
nexus-test_node01    |   File "/bsb/nexus_server/nexus_server.py", line 1800, in distribute_message
nexus-test_node01    |     NEXUS_LXM_SOCKET.send_message(
nexus-test_node01    |   File "/bsb/nexus_server/nexus_server.py", line 745, in send_message
nexus-test_node01    |     self.lxm_router.handle_outbound(lxm_message)
nexus-test_node01    |   File "/usr/local/lib/python3.9/site-packages/LXMF/LXMF.py", line 1110, in handle_outbound
nexus-test_node01    |     self.process_outbound()
nexus-test_node01    |   File "/usr/local/lib/python3.9/site-packages/LXMF/LXMF.py", line 1634, in process_outbound
nexus-test_node01    |     lxmessage.send()
nexus-test_node01    |   File "/usr/local/lib/python3.9/site-packages/LXMF/LXMF.py", line 285, in send
nexus-test_node01    |     receipt.set_delivery_callback(self.__mark_delivered)
nexus-test_node01    | AttributeError: 'bool' object has no attribute 'set_delivery_callback'
nexus-test_node01    | -------------------------------

```

at the code the error was at:

```
    def send(self):
        self.determine_transport_encryption()

        if self.method == LXMessage.OPPORTUNISTIC:
            self.__as_packet().send().set_delivery_callback(self.__mark_delivered)
            self.state = LXMessage.SENT
        
        elif self.method == LXMessage.DIRECT:
            self.state = LXMessage.SENDING

            if self.representation == LXMessage.PACKET:
                receipt = self.__as_packet().send()
->            receipt.set_delivery_callback(self.__mark_delivered)
                receipt.set_timeout_callback(self.__link_packet_timed_out)

            elif self.representation == LXMessage.RESOURCE:
                self.resource_representation = self.__as_resource()

        elif self.method == LXMessage.PROPAGATED:
            self.state = LXMessage.SENDING

            if self.representation == LXMessage.PACKET:
                receipt = self.__as_packet().send()
                if receipt:
                    receipt.set_delivery_callback(self.__mark_propagated)
                    receipt.set_timeout_callback(self.__link_packet_timed_out)
                else:
                    self.__delivery_destination.teardown()

            elif self.representation == LXMessage.RESOURCE:
                self.resource_representation = self.__as_resource()
```

I have no clue why that hapens.
I does not happen all the time, so probably is a kind of corner case when something goes wrong with the send() function above.
The code runs not in my IDE but within a docker container.
And I see that one once in a while ...

Any idea whats happenenig here?
How can the member beeing called not be there?

The callback is set like this:

```
        # Create lxmessage and handle outbound to the target Nexus server with the lxm router
        lxm_message = LXMF.LXMessage(
            to_destination,
            destination_hash=destination_hash,
            source=self.socket_destination,
            content=content,
            title=title,
            fields=fields,
            desired_method=LXMF.LXMessage.DIRECT
        )

        # Register message handler
        # This is the good case - message is processed successfully
        lxm_message.register_delivery_callback(NexusLXMSocket.lxmf_delivery_callback)
        # Log delivery failure
        lxm_message.register_failed_callback(NexusLXMSocket.lxmf_delivery_callback)
```

And of course works for all other messages sent.
So I think it might be a problem somewhere around the receipt handling of LXMF in case something goes wrong or is run in parallel...

Any help would be appreciated.
Cheers
Stephan

**Comment by markqvist** [comment]
Well, this should actually have stayed on the LXMF repo, since it was really just an unhandled case in the LXMF outbound processing. It is fixed now, and will be included in v0.1.6.
